[package]
name = "app"
version = "0.1.0"
edition = "2021"

[lib]
name = "app"
path = "src/lib.rs"

[[bin]]
name = "babelmap"
path = "src/main.rs"

[dependencies]
zvm = { path = "../zvm" }
gvm = { path = "../gvm" }
mapper = { path = "../mapper" }
blorb = { path = "../blorb" }
ratatui = "0.29"
crossterm = "0.28"
zip = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
toml = "0.8"
toml_edit = "0.22"
regex = "1"
clap = { version = "4", features = ["derive"] }
notify = "6"
unicode-width = "0.1"
