//! Educational, per-opcode help for the debugger's instruction tooltip.
//!
//! [`opcode_help`] returns a structured description — a summary, the meaning of
//! each operand, and what the opcode stores/branches on — keyed by the mnemonic
//! string that [`crate::cpu::disasm::mnemonic`] already resolved (so
//! version-specific spellings like `call_1n`/`not` are unambiguous). Grounded in
//! the Z-Machine Standards Document opcode tables.

/// Structured help for one opcode.
pub struct OpcodeHelp {
    /// One-line summary of what the opcode does.
    pub summary: &'static str,
    /// Meaning of each positional operand, in order.
    pub params: &'static [&'static str],
    /// Label for operands beyond `params` — the variadic tail of `je` and the
    /// `call_*` family. `None` for fixed-arity opcodes.
    pub rest: Option<&'static str>,
    /// What the stored result means (phrased to read after "stores"), if the
    /// opcode stores.
    pub returns: Option<&'static str>,
    /// The branch condition (phrased to read after "branches if"), if the opcode
    /// branches.
    pub branch: Option<&'static str>,
}

/// Full per-opcode help keyed by resolved mnemonic. `None` for the `op:*`
/// placeholders (unassigned opcodes).
pub fn opcode_help(name: &str) -> Option<OpcodeHelp> {
    // (summary, params, rest, returns, branch)
    type Row = (&'static str, &'static [&'static str], Option<&'static str>, Option<&'static str>, Option<&'static str>);
    let row: Row = match name {
        // ── 2OP ──────────────────────────────────────────────────────────────
        "je" => ("Branch comparing the first value against the others for equality.",
            &["value to test"], Some("compared against the first"), None,
            Some("any of the other values equals the first")),
        "jl" => ("Branch if a is less than b (signed).",
            &["a", "b"], None, None, Some("a < b")),
        "jg" => ("Branch if a is greater than b (signed).",
            &["a", "b"], None, None, Some("a > b")),
        "dec_chk" => ("Decrement a variable, then compare it against a value.",
            &["variable to decrement (by number)", "value to compare against"], None, None,
            Some("the decremented variable is now < the value")),
        "inc_chk" => ("Increment a variable, then compare it against a value.",
            &["variable to increment (by number)", "value to compare against"], None, None,
            Some("the incremented variable is now > the value")),
        "jin" => ("Test a parent/child relationship between two objects.",
            &["child object", "parent object"], None, None,
            Some("the first object's parent is the second")),
        "test" => ("Test that all of a set of flag bits are present in a bitmap.",
            &["bitmap", "flags to require"], None, None,
            Some("every bit set in the flags is also set in the bitmap")),
        "or" => ("Bitwise OR of two values.",
            &["a", "b"], None, Some("a | b"), None),
        "and" => ("Bitwise AND of two values.",
            &["a", "b"], None, Some("a & b"), None),
        "test_attr" => ("Test whether an object has an attribute set.",
            &["object", "attribute number"], None, None,
            Some("the object has the attribute set")),
        "set_attr" => ("Set an attribute flag on an object.",
            &["object", "attribute number"], None, None, None),
        "clear_attr" => ("Clear an attribute flag on an object.",
            &["object", "attribute number"], None, None, None),
        "store" => ("Write a value into a variable.",
            &["variable to write (by number)", "value to store"], None, None, None),
        "insert_obj" => ("Move an object to become the first child of another.",
            &["object to move", "new parent object"], None, None, None),
        "loadw" => ("Read a word from a word-indexed array.",
            &["array base address", "word index (each step is 2 bytes)"], None,
            Some("the word at base + 2×index"), None),
        "loadb" => ("Read a byte from a byte-indexed array.",
            &["array base address", "byte index"], None,
            Some("the byte at base + index"), None),
        "get_prop" => ("Read an object property, or its default value.",
            &["object", "property number"], None,
            Some("the property value (its default if the object lacks it)"), None),
        "get_prop_addr" => ("Find where an object property's data is stored.",
            &["object", "property number"], None,
            Some("the byte address of the property data (0 if absent)"), None),
        "get_next_prop" => ("Walk an object's property list.",
            &["object", "property number (0 to start)"], None,
            Some("the number of the next property (0 at the end)"), None),
        "add" => ("Signed 16-bit addition.", &["a", "b"], None, Some("a + b"), None),
        "sub" => ("Signed 16-bit subtraction.", &["a", "b"], None, Some("a − b"), None),
        "mul" => ("Signed 16-bit multiplication.", &["a", "b"], None, Some("a × b"), None),
        "div" => ("Signed 16-bit division (truncated toward zero).",
            &["dividend", "divisor (must be nonzero)"], None, Some("dividend ÷ divisor"), None),
        "mod" => ("Signed 16-bit remainder.",
            &["dividend", "divisor (must be nonzero)"], None,
            Some("the remainder of dividend ÷ divisor"), None),
        "call_2s" => ("Call a routine with one argument, keeping the result.",
            &["routine to call"], Some("argument passed to the routine"),
            Some("the routine's return value"), None),
        "call_2n" => ("Call a routine with one argument, discarding the result.",
            &["routine to call"], Some("argument passed to the routine"), None, None),
        "set_colour" => ("Set the text foreground and background colours.",
            &["foreground colour", "background colour"], None, None, None),
        "throw" => ("Unwind the stack back to a frame captured by catch.",
            &["value to return", "frame handle from an earlier catch"], None, None, None),
        // ── 1OP ──────────────────────────────────────────────────────────────
        "jz" => ("Branch if a value is zero.",
            &["value to test"], None, None, Some("the value is zero")),
        "get_sibling" => ("Get an object's next sibling.",
            &["object"], None, Some("the sibling object number (0 if none)"),
            Some("the sibling exists (is nonzero)")),
        "get_child" => ("Get an object's first child.",
            &["object"], None, Some("the child object number (0 if none)"),
            Some("a child exists (is nonzero)")),
        "get_parent" => ("Get an object's parent.",
            &["object"], None, Some("the parent object number (0 if none)"), None),
        "get_prop_len" => ("Find a property's length from its data address.",
            &["property-data address (from get_prop_addr)"], None,
            Some("the property's length in bytes"), None),
        "inc" => ("Add 1 to a variable (signed).",
            &["variable to increment (by number)"], None, None, None),
        "dec" => ("Subtract 1 from a variable (signed).",
            &["variable to decrement (by number)"], None, None, None),
        "print_addr" => ("Print a Z-string stored at a byte address.",
            &["byte address of a Z-string"], None, None, None),
        "call_1s" => ("Call a routine with no arguments, keeping the result.",
            &["routine to call"], None, Some("the routine's return value"), None),
        "remove_obj" => ("Detach an object from its parent.",
            &["object to remove"], None, None, None),
        "print_obj" => ("Print an object's short name.",
            &["object"], None, None, None),
        "ret" => ("Return from the current routine.",
            &["value to return"], None, None, None),
        "jump" => ("Jump unconditionally by a signed offset (not a call).",
            &["signed offset (relative to the next instruction)"], None, None, None),
        "print_paddr" => ("Print a Z-string at a packed string address.",
            &["packed string address"], None, None, None),
        "load" => ("Read a variable's current value.",
            &["variable to read (by number)"], None, Some("the variable's value"), None),
        "call_1n" => ("Call a routine with no arguments, discarding the result.",
            &["routine to call"], None, None, None),
        "not" => ("Bitwise NOT (one's complement).",
            &["value to invert"], None, Some("the bitwise complement of the value"), None),
        // ── 0OP ──────────────────────────────────────────────────────────────
        "rtrue" => ("Return true (1) from the current routine.", &[], None, None, None),
        "rfalse" => ("Return false (0) from the current routine.", &[], None, None, None),
        "print" => ("Print the literal Z-string that follows this opcode.", &[], None, None, None),
        "print_ret" => ("Print the inline Z-string, then a newline, then return true.",
            &[], None, None, None),
        "nop" => ("Do nothing.", &[], None, None, None),
        "save" => ("Save the whole game state.", &[], None,
            Some("whether the save succeeded (v4+)"), Some("the save succeeded (v3)")),
        "restore" => ("Restore game state from a save.", &[], None,
            Some("nonzero only on failure — on success, execution resumes in the restored game"),
            Some("the restore failed (v3)")),
        "restart" => ("Restart the game from the beginning.", &[], None, None, None),
        "ret_popped" => ("Return the top stack value from the current routine.",
            &[], None, None, None),
        "catch" => ("Capture the current call-frame handle for a later throw.",
            &[], None, Some("a handle identifying the current stack frame"), None),
        "pop" => ("Discard the top value on the stack.", &[], None, None, None),
        "quit" => ("End the game immediately.", &[], None, None, None),
        "new_line" => ("Print a newline.", &[], None, None, None),
        "show_status" => ("Redraw the version-3 status line.", &[], None, None, None),
        "verify" => ("Check the story file's checksum.", &[], None, None,
            Some("the file checksum matches the header")),
        "extended" => ("Prefix byte introducing an extended (EXT) opcode.", &[], None, None, None),
        "piracy" => ("The interpreter's 'is this genuine?' check.", &[], None, None,
            Some("the interpreter considers the game genuine (normally taken)")),
        // ── VAR ──────────────────────────────────────────────────────────────
        "call_vs" => ("Call a routine with up to 3 arguments, keeping the result.",
            &["routine to call"], Some("argument passed to the routine"),
            Some("the routine's return value"), None),
        "storew" => ("Write a word into a word-indexed array.",
            &["array base address", "word index (each step is 2 bytes)", "value to store"],
            None, None, None),
        "storeb" => ("Write a byte into a byte-indexed array.",
            &["array base address", "byte index", "byte value to store"], None, None, None),
        "put_prop" => ("Write a value into an object property.",
            &["object", "property number", "value to store"], None, None, None),
        "aread" => ("Read and tokenise a line of input from the player.",
            &["text buffer: typed characters are stored here",
              "parse buffer: tokenised words are written here",
              "time: tenths of a second before the timeout routine fires (0 = no timeout)",
              "routine: called on each timeout; return true to end input"], None,
            Some("the key that terminated input (13 = Return; a function-key code in v5+)"), None),
        "sread" => ("Read and tokenise a line of input from the player. (v1–4)",
            &["text buffer: typed characters are stored here",
              "parse buffer: tokenised words are written here",
              "time: tenths of a second before the timeout routine fires (v4)",
              "routine: called on each timeout (v4)"], None, None, None),
        "print_char" => ("Print one ZSCII character.",
            &["ZSCII character code"], None, None, None),
        "print_num" => ("Print a signed number in decimal.",
            &["value to print"], None, None, None),
        "random" => ("Get a random number, or seed the generator.",
            &["range: if >0, return 1..range; if ≤0, (re)seed with this value"], None,
            Some("a random number in 1..range (0 when seeding)"), None),
        "push" => ("Push a value onto the game stack.",
            &["value to push"], None, None, None),
        "pull" => ("Pop the top of the stack into a variable.",
            &["variable to receive the value (by number)"], None, None, None),
        "split_window" => ("Create an upper window of a given height.",
            &["number of lines for the upper window"], None, None, None),
        "set_window" => ("Choose which window receives output.",
            &["window (0 = lower, 1 = upper)"], None, None, None),
        "call_vs2" => ("Call a routine with up to 7 arguments, keeping the result.",
            &["routine to call"], Some("argument passed to the routine"),
            Some("the routine's return value"), None),
        "erase_window" => ("Clear a window.",
            &["window (−1 = whole screen, −2 = screen without unsplitting)"], None, None, None),
        "erase_line" => ("Erase from the cursor to the end of the line.",
            &["value (1 = erase to end of line)"], None, None, None),
        "set_cursor" => ("Move the cursor in the upper window.",
            &["row (1-based)", "column (1-based)"], None, None, None),
        "get_cursor" => ("Store the current cursor position.",
            &["array to receive row then column"], None, None, None),
        "set_text_style" => ("Set the text style.",
            &["style bits (0 roman, 1 reverse, 2 bold, 4 italic, 8 fixed-pitch)"], None, None, None),
        "buffer_mode" => ("Turn word-wrap buffering of the lower window on or off.",
            &["flag (1 = buffer/word-wrap, 0 = off)"], None, None, None),
        "output_stream" => ("Enable or disable an output stream.",
            &["stream (+ enable / − disable: 1 screen, 2 transcript, 3 table, 4 commands)"],
            Some("for stream 3, the table address to capture into"), None, None),
        "input_stream" => ("Choose the input stream.",
            &["stream (0 = keyboard, 1 = command file)"], None, None, None),
        "sound_effect" => ("Play a sound effect or bleep.",
            &["sound number (1–2 = bleeps)",
              "effect (1 prepare, 2 start, 3 stop, 4 finish)",
              "volume (and repeats, high byte)",
              "routine to call when the sound finishes"], None, None, None),
        "read_char" => ("Read a single keypress.",
            &["device (must be 1 = keyboard)",
              "time: tenths of a second before the timeout routine fires",
              "routine: called on each timeout; return true to end input"], None,
            Some("the ZSCII code of the key pressed"), None),
        "scan_table" => ("Search a table for a value.",
            &["value to find", "table address", "number of entries",
              "entry format (bit 7 = word/byte entries, low bits = entry length)"], None,
            Some("the address where the value was found (0 if absent)"),
            Some("the value was found")),
        "call_vn" => ("Call a routine with up to 3 arguments, discarding the result.",
            &["routine to call"], Some("argument passed to the routine"), None, None),
        "call_vn2" => ("Call a routine with up to 7 arguments, discarding the result.",
            &["routine to call"], Some("argument passed to the routine"), None, None),
        "tokenise" => ("Tokenise text already in a buffer against a dictionary.",
            &["text buffer to read", "parse buffer to fill",
              "dictionary to use (0 = the game's)", "flag (1 = leave unknown words unchanged)"],
            None, None, None),
        "encode_text" => ("Encode text into packed dictionary form.",
            &["byte address of the ZSCII text", "number of characters",
              "offset of the first character", "buffer to receive the encoded word"],
            None, None, None),
        "copy_table" => ("Copy or zero a block of memory.",
            &["source table (0 = zero the destination instead)", "destination table",
              "size in bytes (negative forces a strictly forward copy)"], None, None, None),
        "print_table" => ("Print a rectangular block of text from memory.",
            &["text address", "width in characters", "height in lines (default 1)",
              "skip: bytes to advance between lines"], None, None, None),
        "check_arg_count" => ("Test whether an argument was supplied to this routine.",
            &["argument number (1-based)"], None, None,
            Some("that argument was actually passed")),
        // ── EXT ──────────────────────────────────────────────────────────────
        "log_shift" => ("Logical (unsigned) bit shift.",
            &["value to shift", "shift amount (positive = left, negative = right)"], None,
            Some("the shifted value (zeros shifted in)"), None),
        "art_shift" => ("Arithmetic (signed) bit shift.",
            &["value to shift", "shift amount (positive = left, negative = right)"], None,
            Some("the shifted value (sign preserved on right shifts)"), None),
        "set_font" => ("Choose a text font.",
            &["font number (1 = normal, 3 = character graphics, 4 = fixed-pitch)"], None,
            Some("the previous font, or 0 if the requested font is unavailable"), None),
        "save_undo" => ("Save an in-memory undo snapshot.",
            &[], None,
            Some("1 on success, 0 if undo is unsupported, −1 in the restored state"), None),
        "restore_undo" => ("Restore the most recent undo snapshot.",
            &[], None,
            Some("nonzero only on failure — on success, execution resumes in the restored state"), None),
        "print_unicode" => ("Print one Unicode character.",
            &["Unicode code point"], None, None, None),
        "check_unicode" => ("Ask whether a Unicode character is usable.",
            &["Unicode code point"], None,
            Some("bit 0 set = can print it, bit 1 set = can read it"), None),
        "set_true_colour" => ("Set text colours using 15-bit RGB values.",
            &["foreground colour (−1 = default, −2 = keep current)", "background colour"],
            None, None, None),
        // v6 graphics/window opcodes. v6 stories boot text-only (SQ-0186 Phase 0);
        // these opcodes are stubbed pending the v6 window/graphics phases.
        "draw_picture" => ("Draw a picture on the screen. (v6)",
            &["picture number", "row", "column"], None, None, None),
        "picture_data" => ("Query a picture's size and availability. (v6)",
            &["picture number", "array to receive height and width"], None, None,
            Some("the picture (or picture directory) exists")),
        "erase_picture" => ("Erase a picture from the screen. (v6)",
            &["picture number", "row", "column"], None, None, None),
        "set_margins" => ("Set a window's left and right margins. (v6)",
            &["left margin", "right margin", "window"], None, None, None),
        "move_window" => ("Move a window on the screen. (v6)",
            &["window", "row", "column"], None, None, None),
        "window_size" => ("Resize a window. (v6)",
            &["window", "height", "width"], None, None, None),
        "window_style" => ("Set window style flags. (v6)",
            &["window", "style flags", "operation (set/clear/…)"], None, None, None),
        "get_wind_prop" => ("Read a window property. (v6)",
            &["window", "property number"], None, Some("the property value"), None),
        "scroll_window" => ("Scroll a window vertically. (v6)",
            &["window", "pixels (negative scrolls the other way)"], None, None, None),
        "pop_stack" => ("Discard values from a stack. (v6)",
            &["number of items to discard", "stack address (0 = the game stack)"], None, None, None),
        "read_mouse" => ("Read the mouse position and buttons. (v6)",
            &["array to receive y, x, button state and menu"], None, None, None),
        "mouse_window" => ("Confine the mouse to a window. (v6)",
            &["window (−1 = the whole screen)"], None, None, None),
        "push_stack" => ("Push a value onto a user stack. (v6)",
            &["value to push", "user stack address"], None, None,
            Some("there was room on the stack")),
        "put_wind_prop" => ("Write a window property. (v6)",
            &["window", "property number", "value"], None, None, None),
        "print_form" => ("Print a formatted table of text. (v6)",
            &["formatted-table address"], None, None, None),
        "make_menu" => ("Create or remove a menu. (v6)",
            &["menu number", "table of menu items (0 = remove the menu)"], None, None,
            Some("the menu operation succeeded")),
        "picture_table" => ("Preload a set of pictures for faster drawing. (v6)",
            &["table of picture numbers"], None, None, None),
        "buffer_screen" => ("Control deferred screen redraws. (v6)",
            &["mode (−1 = query the current mode)"], None,
            Some("the previous buffering mode"), None),
        _ => return None,
    };
    Some(OpcodeHelp { summary: row.0, params: row.1, rest: row.2, returns: row.3, branch: row.4 })
}

/// One-line summary of an opcode (the `summary` field of [`opcode_help`]).
pub fn describe_mnemonic(name: &str) -> Option<&'static str> {
    opcode_help(name).map(|h| h.summary)
}
