//! The two flags every CLI answers the same way.
//!
//! `--help` and `--version` are handled before anything else is set up: no
//! story is loaded, no terminal is touched, and the exit is a plain return so a
//! `--help` in a pipeline stays clean.
//!
//! The name and version are passed in rather than read here, because
//! `env!("CARGO_PKG_NAME")` and `buildinfo::LONG` must expand in the *binary's*
//! crate — a copy baked into this one would report `cli-host` for all three.

/// The arguments before the first `--`, which ends option parsing.
///
/// `args::scan` already honours `--` — everything after it is positional even
/// when it is spelled like a flag — and the pre-scans that run before `scan`
/// (this module's [`handled_common_flags`], `mode::plain_from`) must agree, or
/// `zvm-cli -- --help` prints the help instead of opening a story literally
/// named `--help`.
pub fn before_double_dash(argv: &[String]) -> impl Iterator<Item = &String> {
    argv.iter().take_while(|a| a.as_str() != "--")
}

/// Handle `--help`/`-h` and `--version`/`-V` if present.
///
/// Returns `true` when one was handled and the caller should return from `main`
/// immediately. Help wins over version when both are given, matching the order
/// the CLIs checked them in before. Stops at `--`: past it these spellings are
/// story paths, not flags.
pub fn handled_common_flags(argv: &[String], help: &str, name: &str, version: &str) -> bool {
    if before_double_dash(argv).any(|a| a == "--help" || a == "-h") {
        print!("{help}");
        return true;
    }
    if before_double_dash(argv).any(|a| a == "--version" || a == "-V") {
        println!("{name} {version}");
        return true;
    }
    false
}

/// Exit code for a command-line usage error.
///
/// 2 is the shell convention for "you invoked this wrongly" (and what
/// getopt-based tools use), distinct from 1, which these binaries already use
/// for a story that could not be read or parsed. Worth keeping apart: one means
/// fix your command, the other means fix your file.
pub const EXIT_USAGE: i32 = 2;

/// Report a usage error, print the help, and exit.
///
/// Showing the help matters more than it looks. A mistyped flag used to be
/// silently ignored by `zvm-cli` and `gvm-cli` — `--no-statu` did nothing at all
/// and exited 0 — so the failure mode was a player concluding the feature was
/// broken rather than the spelling. Naming the offending argument and then
/// listing what is actually accepted answers both questions at once.
pub fn usage_error(name: &str, message: &str, help: &str) -> ! {
    eprintln!("{name}: {message}");
    eprintln!();
    eprint!("{help}");
    std::process::exit(EXIT_USAGE)
}

/// The one width every `--help` in this workspace wraps to (SQ-1093).
///
/// A fixed 80, not the terminal's own width, and the same number for all four
/// front-ends — `lanthorn`'s clap-rendered help and the three hand-written
/// `HELP` constants alike. Two authorities were in play and one `--help` showed
/// both: `zvm-cli`'s prose was hand-wrapped to ~83 columns while the disk-format
/// list it substitutes in was generated by joining a `Vec` and ran to 117, so
/// the right margin was ragged in a way that reads as a rendering fault.
///
/// 80 because a help is read as often through `| less` and `> file` as on a
/// screen, and neither of those has a width; because a narrow terminal is the
/// one that suffers when the text is wider than it; and because a paragraph
/// reflowed to a 200-column window is not readable prose at any rate. The cost
/// is a wide screen's unused right half, which is what every man page already
/// spends.
///
/// Pinned by a test in each of the four crates, through [`overlong_help_lines`].
pub const HELP_WIDTH: usize = 80;

/// Every line of `help` wider than [`HELP_WIDTH`], as `(1-based line, width)`.
///
/// Measured in `chars`, not bytes: these texts are full of em-dashes, and a
/// byte count would report every paragraph containing one as three columns too
/// wide. Empty when the text obeys the width, which is what the four tests
/// assert.
pub fn overlong_help_lines(help: &str) -> Vec<(usize, usize)> {
    help.lines()
        .enumerate()
        .map(|(i, l)| (i + 1, l.chars().count()))
        .filter(|(_, w)| *w > HELP_WIDTH)
        .collect()
}

/// Lay `tokens` out on lines no wider than [`HELP_WIDTH`], never breaking INSIDE
/// a token, with every line after the first indented by `indent` (SQ-1093).
///
/// For the runs of help text that are GENERATED rather than typed — `zvm-cli`
/// substitutes the disk formats it recognises and the machines they imply, from
/// `blorb::medium`'s table, so a new row reaches the help with no edit. Those
/// were joined with `", "` and printed, which is a line nothing measured: the
/// extension list had reached 117 columns and ran off the edge in the middle of
/// a help whose every other line was hand-wrapped to about 83.
///
/// A token, not a word, because `ADF 4` is one fact and a line break between the
/// label and its interpreter number would read as two.
pub fn wrap_tokens<S: AsRef<str>>(tokens: &[S], indent: usize) -> String {
    let mut out = String::new();
    let mut col = indent;
    for (i, t) in tokens.iter().enumerate() {
        let t = t.as_ref();
        let w = t.chars().count();
        if i == 0 {
            // The caller's placeholder already sits at `indent`.
        } else if col + 1 + w > HELP_WIDTH {
            out.push('\n');
            out.push_str(&" ".repeat(indent));
            col = indent;
        } else {
            out.push(' ');
            col += 1;
        }
        out.push_str(t);
        col += w;
    }
    out
}

/// Read an `on`/`off` value for a symmetric switch (SQ-1082).
///
/// `None` means the flag was not typed at all, and that is a THIRD answer, not a
/// quiet `off`: every one of these flags overrides a setting that persists, so a
/// flag's absence has to leave a stored `true` alone as surely as a stored
/// `false`. A negative-only `--no-sound` could only ever say one of the two, so
/// a config carrying `enable_sound = false` had no command line that could
/// override it.
///
/// The value is required — `--sound on`, never a bare `--sound` — because a bare
/// form invites "is that on, or is it a toggle?", which is the ambiguity this
/// spelling exists to remove.
pub fn on_off(name: &str, value: Option<&str>) -> Result<Option<bool>, String> {
    match value {
        None => Ok(None),
        Some("on") => Ok(Some(true)),
        Some("off") => Ok(Some(false)),
        Some(v) => Err(format!("{name} takes on or off, got '{v}'")),
    }
}

/// Does `arg` look like a flag rather than a positional argument?
///
/// A bare `-` is conventionally stdin, not a flag, so it is left to the caller.
/// Everything else starting with `-` is a flag — including single-dash forms,
/// which `zvm-cli` previously fell through to its story-path arm, so `-x` was
/// taken as a filename and reported as a missing file.
pub fn looks_like_flag(arg: &str) -> bool {
    arg.len() > 1 && arg.starts_with('-')
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn a_lone_dash_is_not_a_flag() {
        assert!(!looks_like_flag("-"), "bare - is conventionally stdin");
        assert!(!looks_like_flag(""));
        assert!(!looks_like_flag("story.z5"));
        assert!(looks_like_flag("-x"), "single-dash forms are flags, not filenames");
        assert!(looks_like_flag("--plain"));
        assert!(looks_like_flag("--"), "-- is not a path either");
    }

    fn argv(args: &[&str]) -> Vec<String> {
        args.iter().map(|s| s.to_string()).collect()
    }

    #[test]
    fn recognises_both_spellings_of_each_flag() {
        for a in ["--help", "-h", "--version", "-V"] {
            assert!(
                handled_common_flags(&argv(&["prog", a]), "", "", ""),
                "{a} should be handled"
            );
        }
    }

    #[test]
    fn ordinary_invocation_is_not_handled() {
        assert!(!handled_common_flags(&argv(&["prog", "story.z5"]), "", "", ""));
        assert!(!handled_common_flags(&argv(&["prog"]), "", "", ""));
        // A flag that merely contains one of the names is not it.
        assert!(!handled_common_flags(&argv(&["prog", "--help-me"]), "", "", ""));
        // Nor is a story file that happens to be spelled like one.
        assert!(!handled_common_flags(&argv(&["prog", "-help"]), "", "", ""));
    }

    #[test]
    fn a_flag_anywhere_in_the_line_counts() {
        assert!(handled_common_flags(&argv(&["prog", "story.z5", "--help"]), "", "", ""));
    }

    /// SQ-1082. The three answers a symmetric switch has, and the fact that a
    /// missing value is refused rather than guessed at.
    #[test]
    fn on_off_keeps_absent_distinct_from_off() {
        assert_eq!(on_off("--sound", None), Ok(None), "not mentioned is not off");
        assert_eq!(on_off("--sound", Some("on")), Ok(Some(true)));
        assert_eq!(on_off("--sound", Some("off")), Ok(Some(false)));
        assert_eq!(
            on_off("--sound", Some("yes")),
            Err("--sound takes on or off, got 'yes'".to_string())
        );
    }

    /// SQ-1093. A generated run wraps at the same width as the prose around it,
    /// and never inside a fact.
    #[test]
    fn generated_help_runs_wrap_at_the_shared_width() {
        let exts: Vec<String> = (0..30).map(|i| format!(".ext{i:02},")).collect();
        let wrapped = wrap_tokens(&exts, 26);
        for (i, line) in wrapped.lines().enumerate() {
            let col = if i == 0 { 26 } else { 0 };
            assert!(col + line.chars().count() <= HELP_WIDTH, "line {i}: {line}");
        }
        assert!(wrapped.lines().count() > 1, "the fixture is long enough to need wrapping");
        assert!(wrapped.lines().skip(1).all(|l| l.starts_with(&" ".repeat(26))));
        // A token with a space in it is one fact and is never split.
        let pairs = ["ADF 4,".to_string(), "HFS 3".to_string()];
        assert_eq!(wrap_tokens(&pairs, 26), "ADF 4, HFS 3");
        assert_eq!(wrap_tokens::<String>(&[], 26), "");
    }

    /// SQ-1093. The measurement the four help tests share, and the em-dash trap
    /// it exists to avoid: a byte count reports this line as over-wide and it is
    /// not.
    #[test]
    fn overlong_lines_are_measured_in_columns_not_bytes() {
        let dashes = "—".repeat(HELP_WIDTH);
        assert!(dashes.len() > HELP_WIDTH, "three bytes each");
        assert!(overlong_help_lines(&dashes).is_empty(), "but one column each");
        assert_eq!(overlong_help_lines(&format!("{dashes}—")), vec![(1, HELP_WIDTH + 1)]);
        assert_eq!(overlong_help_lines("a
b
"), vec![]);
    }

    /// SQ-0636. `args::scan` treats everything after `--` as positional, so the
    /// pre-scan must too — `zvm-cli -- --help` is a request to open a story
    /// literally named `--help`, not to print the help.
    #[test]
    fn double_dash_ends_the_pre_scan() {
        for a in ["--help", "-h", "--version", "-V"] {
            assert!(
                !handled_common_flags(&argv(&["prog", "--", a]), "", "", ""),
                "{a} after -- is a story path, not a flag"
            );
        }
        // Before the `--` it is still the flag.
        assert!(handled_common_flags(&argv(&["prog", "--help", "--", "x"]), "", "", ""));
    }
}
